.\" The following commands are required for all man pages.
.Dd November 08, 2016
.Dt SIGWINCH 7
.Os HTTP 1.1
.Sh NAME
.Nm sigwinch
.Nd Joe Harrison, postgraduate computer scientist.
.\" This next command is for sections 2 and 3 only.
.\" .Sh LIBRARY
.Sh SYNOPSIS
.Nm
.Ar message ...
.Sh DESCRIPTION
.Nm
is signal 28, a window size change.
.Pp
.Nm
is also a PhD student at the University of Kent, researching communication failures
in distributed actor systems.
.\" .Sh IMPLEMENTATION NOTES
.\" This next command is for sections 1, 6, 7 and 8 only.
.Sh ENVIRONMENT
.Bl -tag -width LOCATION
.It Ev LOCATION
.Dq Canterbury, United Kingdom
.It Ev INSTITUTION
.Dq University of Kent, United Kingdom
.It Ev HOMETOWN
.Dq York, United Kindgom
.El
.\" .Sh FILES
.\" .Sh EXAMPLES
.\" This next command is for sections 1, 6, 7, 8 and 9 only
.\"     (command return values (to shell) and
.\"     fprintf/stderr type diagnostics).
.\" .Sh DIAGNOSTICS
.Sh COMPATIBILITY
.Nm
is fully compatible with the following languages:
.Bd -filled -offset indent
Go,
Erlang,
Python.
.Ed
.Pp
.Nm
has partial support for the following languages:
.Bd -filled -offset indent
C,
Haskell.
.Ed
.Sh SEE ALSO
.Bl -item
.It
.Lk https://www.cs.kent.ac.uk/~jrh53 Academic Homepage
.It
.Lk https://github.com/sigwinch28 GitHub
.It
.Lk https://facebook.com/sigwinch Facebook
.It
.Lk https://twitter.com/sigwinch28 Twitter
.It
.Lk https://www.linkedin.com/in/sigwinch LinkedIn
.El
.Sh STANDARDS
.Bl -tag -width indent
.It Amateur Foundation Radio Licence
Callsign: M6LOX
.El
.\" .Sh HISTORY
.Sh HISTORY
.Bl -tag -width "Sep 2011 - Jul 2015"
.It Sep 2015 - Present
Computer Science PhD
\(em
.Lk https://kent.ac.uk/ University of Kent
.It Jul 2013 - Aug 2014
Technical Student
\(em
.Lk https://home.cern/ CERN
.It Sep 2011 - Jul 2015
Computer Science with a Year in Industry BSc (Hons)
\(em
.Lk https://kent.ac.uk/ University of Kent
.D1 First-class honours
.El
.\" .Sh AUTHORS
.Sh AUTHORS
.An Joe Harrison Aq Mt joe@sigwinch.uk , Mt jrh53@kent.ac.uk
.Sh BUGS
.Bl -item
.It
The PhD task has not been completed.
.It
The PUBLICATIONS section is nonexistent.
.El
